### ISSUE TITLE
[haxelib] Update to 1.0.4

### ISSUE THREAD

**Issue by SlavaRa** [HaxeFoundation/as3hx#181]
i created release 1.0.4 and and I thought that it will automatically updated in the haxelib, but that did not happen.
@Simn @andyli @jgranick please help me. thanks.

**Comment by SlavaRa** [comment]
guys @Simn  @andyli  @andyli  @ncannasse  how i can make new release, please help for me

**Comment by andyli** [comment]
From the [haxelib.json](http://lib.haxe.org/p/as3hx/1.0.3/files/as3hx/haxelib.json) file of the latest haxelib release, it is owned by @jgranick, thus only he can make a new release.

I think it make sense to add @SlavaRa to the list of contributors in haxelib.json in the next release, such that both of you can release updates.

For the release process, read the "Submission process" at the bottom of http://lib.haxe.org/documentation/creating-a-haxelib-package/
