### ISSUE TITLE
Getters and setters capitalization

### ISSUE THREAD

**Issue by neurofuzzy** [HaxeFoundation/as3hx#21]
It appears that the letter after get_ and set_ is being capitalized:

```
public var rotation(get, never):Float;
private function get_Rotation():Float { };
```

But the compiler is looking for `get_rotation` so it cannot find it.

**Comment by giabao** [comment]
you can config: using `%i` instead of `%I`. see [Config.hx](/HaxeFoundation/as3hx/blob/master/src/as3hx/Config.hx)
```xml
    <getterMethods value="get_%i" />
    <setterMethods value="set_%i" />
```
