### ISSUE TITLE
Error new Dynamic()

### ISSUE THREAD

**Issue by flashultra** [HaxeFoundation/as3hx#250]
The "new Dynamic()"  should be translate as "{}" in haxe generated code

**Comment by SlavaRa** [comment]
You are using a library from git or haxelib?

**Comment by flashultra** [comment]
Git version

**Comment by SlavaRa** [comment]
please give me actionscript3 code

**Comment by flashultra** [comment]
AS3 code
`package 
{

	public class Test
	{
		public function Test()
		{
			var params:Object = new Object();
		}
		
		protected function onTest(  ):void
		{
			
			var params:Object = new Object();
		}
	}
}`

Haxe generateed code: 
`
class Test
{
    public function new()
    {
        var params : Dynamic = new Dynamic();
    }
    
    private function onTest() : Void
    {
        
        var params : Dynamic = new Dynamic();
    }
}
`

**Comment by SlavaRa** [comment]
https://github.com/HaxeFoundation/as3hx/pull/251
I added test for this issue. But this conversion works in git version
