### ISSUE TITLE
Wrong version in haxelib

### ISSUE THREAD

**Issue by guifes** [HaxeFoundation/as3hx#260]
I've just downloaded 1.0.3 version from haxelib and a couple of things are wrong. First, my project can't find as3hx source because it's in a src/ folder inside the lib folder. I had to manually copy as3hx to the root of the lib folder for it to work correctly.

Also, the version I downloaded from haxelib has a typo that's not currently present in the github version:

public static inline function **setArrayLegth**<T>(a:Array<T>, length:Int)

**Comment by andyli** [comment]
At the moment only @jgranick has the haxelib submit right. So, assigned him to fix this.

**Comment by mastef** [comment]
@jgranick would you mind updating the haxelib version of as3hx pretty please? :)

**Comment by jgranick** [comment]
I added AS3HX to our automated nightly builds

http://builds.openfl.org/?dir=as3hx

I also released the tagged older 1.0.4 release and the current 1.0.5 release on haxelib
