### ISSUE TITLE
Assigning to anonymous object in an array, index expression confused with RHS

### ISSUE THREAD

**Issue by jcward** [HaxeFoundation/as3hx#261]
Under some conditions, assigning values to an anonymous object in an array using an index into the array, the index values are being assigned instead of the actual right-hand values.

as3 code for example:
```actionscript
package {
    public class Issue {
        public function Issue() {
            //code here...
            var arr:Array = [];
            arr.push(new Data());
            arr.push(new Data());
         
            var chains:Array = [];
            for each (var data:Data in arr) {
              if (data.value==1) continue;
              // Push an object into chains
              chains.push({
                min_value: data.value,
                names: [ data.toString() ]
              });
              // - - - Here are the lines showing the issue - - -
              chains[chains.length-1]["number"] = 555;
              chains[chains.length-2]["data"] = data;
              chains[chains.length-3]["as_array"] = [data];
              // - - - - - - - - - - - - - - - - - - - - - - - -
            }
        }
    }
}

class Data {
  public var value:int;
  public function Data():void {
    value = Math.random()*1000;
  }
  public function toString():String { return '[Data:'+value+']'; }
}
```

Expected result:
```haxe
...
// - - - Here are the lines showing the issue - - -
Reflect.setField(chains[chains.length - 1], "number", 555);
Reflect.setField(chains[chains.length - 2], "data", data);
Reflect.setField(chains[chains.length - 3], "as_array", [data]);
...
```

Actual result:
```haxe
...
// - - - Here are the lines showing the issue - - -
Reflect.setField(chains[chains.length - 1], "number", 1);
Reflect.setField(chains[chains.length - 2], "data", 2);
Reflect.setField(chains[chains.length - 3], "as_array", 3);
...
```

The expression in the array index is somehow polluting the RHS value.

**Comment by jcward** [comment]
Ah, I've narrowed it down to the array access. This produces the expected result:

```actionscript
      chains[0]["number"] = 456;
      chains[0]["an_array"] = [dat];
```

But this does not:
```actionscript
      chains[chains.length-2]["number"] = 456;
      chains[chains.length-2]["an_array"] = [dat];
```

It produces:
```haxe
  Reflect.setField(chains[chains.length - 2], "number", 2);
  Reflect.setField(chains[chains.length - 2], "an_array", 2);
```

**Comment by jcward** [comment]
After just a quick glance at the code, I'm confused how `rvalue` is a [member variable](https://github.com/HaxeFoundation/as3hx/blob/master/src/as3hx/Writer.hx#L39) of [Writer.hx](https://github.com/HaxeFoundation/as3hx/blob/master/src/as3hx/Writer.hx), (though [here](https://github.com/HaxeFoundation/as3hx/blob/master/src/as3hx/Writer.hx#L1552) and [there](https://github.com/HaxeFoundation/as3hx/blob/master/src/as3hx/Writer.hx#L2611) it's locally scoped, yikes) while Writer uses recursive `writeExpr` calls, some of which alter rvalue. How is this not colliding all over the place?

**Comment by RealyUniqueName** [comment]
SlavaRa (maintainer) is away till next week. He told me he will be able to check issues on next week.

**Comment by jcward** [comment]
Thanks for the note. Luckily it's not urgent for me. :) It's only happened once and it's easy to fix by hand.
