### ISSUE TITLE
Option to allow for custom replacements after compilation

### ISSUE THREAD

**Issue by mastef** [HaxeFoundation/as3hx#262]
Might be good to have an inbuilt replacer as option to let the user define common replacements after the file has been converted. And/or option to run a post-script on the file

Common replacements could be e.g. : `import flash.` -> `import openfl.`

If a post-processing command is defined in the config, it would run after the `.hx` file is created - e.g. `post-process.sh output/filename.hx`

**Comment by SlavaRa** [comment]
Not everyone uses openfl, you can use `remap` in your project

**Comment by mastef** [comment]
Right, that was just an example. It's more about having a generic option for simple replacements in as3hx. I've submitted a PR that allows post-processing instead.

**Comment by mastef** [comment]
Basically the main need for me in terms of a post-processor is that I want to replace common class name changes, fix Dynamic method return types, fix incompatible `addFramescript()` multiple arguments input and assign missing types to class vars. Also fix some common casts that I don't want to have in the finished file ( e.g. `(try cast(this.parent, MovieClip) catch(e:Dynamic) null).something` which will crash anyway.

Some of those changes need more advanced logic, so I feel that those are not fully in the scope of `as3hx`. That's why I would prefer if we could just run a post-processing script on each file if it's specified in the config. This would keep it simple

I have tested and working already in PR #263 and it's working nicely.

**Comment by mastef** [comment]
@SlavaRa any chance to merge this? Would love to use this with the team without having to use a fork. We're porting thousands of as3 files currently and this fixes many common issues that shouldn't be tackled in as3hx core ( like a replace engine )

**Comment by SlavaRa** [comment]
@mastef  I will write after the main work, tonight

**Comment by mastef** [comment]
@SlavaRa I hope you're not still at work 😟

**Comment by mastef** [comment]
Thanks!
