### ISSUE TITLE
comments on wrong line and inverted

### ISSUE THREAD

**Issue by SmerkyG** [HaxeFoundation/as3hx#27]
/\* often gets put on prior line, and if the prior line had a // that makes the block comment get commented out!

multiple // comments in a row often (always?) come out in inverted order
comments // and first line of /\* are indented even if they weren't originally

comments // are often put on same line as end of prior scope end }

**Comment by giabao** [comment]
```as3
if (condition) single_statement;

//some comment
other_statements;
```
will be convert to an hx code which can not be compiled:
```haxe
if (condition) single_statement //some comment ;

other_statements;
```
(the comment is place before the semicolon)

**Comment by jgranick** [comment]
This seems like the same issue I encountered, where documented code ended up making things angry :smile:

It was this file:

https://github.com/nadako/SQ-TestTask-Farm/blob/master/thirdparty/interactivePNG/com/mosesSupposes/bitmap/InteractivePNG.as
