### ISSUE TITLE
for loop condition getting cached (as3 for loop doesn't cache max/length, but haxe does)

### ISSUE THREAD

**Issue by sbijoshj** [HaxeFoundation/as3hx#296]
as3 code for example:
```actionscript
package {
    public class Issue {
        public function Issue() {
            var myItems:Array = [1,2,3,4];
            var specialItem:int = 3;
            // in actionscript this max value is not cached, and is reevaluated every time
            for(var i:int = 0; i < myItems.length; i++)
            {
                if(myItems[i] == specialItem)
                {
                    // by design, remove and skip over next item
                    myItems.splice(i,1);  // this changes the array length
                }
            }
        }
    }
}

```
expected result (while loop currently isn't cached by haxe to javascript translation, but maybe there is a better way to do this...)
```haxe

class Issue
{
    public function new()
    {
        var myItems:Array<Int> = [1,2,3,4];
        var specialItem:Int = 3;
        // in actionscript this max value is not cached, and is reevaluated every time
        var i:Int = 0;
        while (i < myItems.length)
        {
            if(myItems[i] == specialItem)
            {
                // by design, remove and skip over next item
                myItems.splice(i,1);  // this changes the array length
            }
            i++;
        }
    }
}

```
actual result
```haxe

class Issue
{
    public function new()
    {
        var myItems : Array<Dynamic> = [1, 2, 3, 4];
        var specialItem : Int = 3;
        // in actionscript this max value is not cached, and is reevaluated every time
        for (i in 0...myItems.length)
        {
            if (myItems[i] == specialItem)
            
            // by design, remove and skip over next item{
                
                myItems.splice(i, 1);
            }
        }
    }
}

```

**Comment by mastef** [comment]
So basically this consists of 3 checks : 
- check if a var of type `Array` is a condition in a `for` loop
- check if `length` property is also part of the `for` loop condition
- check if within the `for` loop any array modifiers are used with the array var

if `(a && b && c)` change for loop to `while` loop to match as3 behaviour

What qualifies as array modifiers? 
`loopArray =`
`loopArray.insert`
`loopArray.pop`
`loopArray.push`
`loopArray.remove`
~`loopArray.reverse`~ ( only changes order )
`loopArray.shift`
~`loopArray.slice`~ ( doesn't modify `this` array )
~`loopArray.sort`~ ( only changes order )
`loopArray.splice`
`loopArray.unshift`

Anything I missed? I'm thinking of `Reflect.*` methods like `deleteField` and `deleteProperty`, but that should be rather edge-cases.

**Comment by SlavaRa** [comment]
We can not foresee all the situations, but we can add option `-for2while`

**Comment by SlavaRa** [comment]
code:
```actionscript3
// in actionscript this max value is not cached, and is reevaluated every time
for(var i:int = 0; i < myItems.length; i++)
{
	if(myItems[i] == specialItem)
	{
		// by design, remove and skip over next item
		myItems.splice(i,1);  // this changes the array length
	}
}
```
very strange and dangerous :)

**Comment by mastef** [comment]
Ah, you mean, if any `array.length` is found, then just change to a while loop?
Yeah the `i++` insertion is tricky, because some statements can have a `continue`

**Comment by SlavaRa** [comment]
>>>Ah, you mean, if any array.length is found, then just change to a while loop?
```for(var i = 0; i < myItems.length; i++)```
```for(var i = 0; i < container.numChildren; i++)```
```for(var i = 0; i < someFunction(); i++)```
...
except:
```for(var i = 0; i < const_value; i++)```

**Comment by mastef** [comment]
Yeah, lots of issues. Ideally such for loops would end up as : 
```
for (var i = 0; i < arr.length; i++) {
	trace(arr[i]);
	if(arr[i].removeMe) arr.splice(i,1);
}
```
-> 
```
for (v in arr) {
	trace(v);
	if(v.removeMe) arr.remove(v);
}
```
But that introduces many other issues. E.g. `arr.remove(v)` removing the `first`(!) occurence of `v` from `arr`. 😐 

Also in general after an `arr.splice(i, 1)` in a for loop we'd need to `i--` ( e.g. `arr.splice(i--, 1)` ), since the next item would be skipped otherwise.

**Comment by mastef** [comment]
I take the comment back - `for (v in arr) {` is unreliable when `arr.splice` happens inside the loop! The iterator must be doing the same index iteration as the other for loop. That was unexpected. https://try.haxe.org/#F2A39

**Comment by mastef** [comment]
oh wow!

**Comment by SlavaRa** [comment]
👍

**Comment by sbijoshj** [comment]
:tada:
