### ISSUE TITLE
pls help, get errors on windows

### ISSUE THREAD

**Issue by Helgiii** [HaxeFoundation/as3hx#320]
so i updated with haxelib update
did haxelib install as3hx
also installed gnu make (just to be sure)

in the as3hx folder i ran haxe -debug as3hx.hxml
it seems to do something but has no output in console

then i call neko run.n test/ out/
and it fails, see console output:

c:\HaxeToolkit\haxe\lib\as3hx\1,0,6>neko run.n test/ out/
Called from ? line 1
Called from Run.hx line 110
Called from Run.hx line 32
Called from C:\HaxeToolkit\haxe\std/neko/_std/sys/FileSystem.hx line 94
Uncaught exception - std@sys_read_dir

c:\HaxeToolkit\haxe\lib\as3hx\1,0,6>

**Comment by SlavaRa** [comment]
Today

**Comment by Helgiii** [comment]
removing the "out" dir solves the problem
just as adviced here https://github.com/HaxeFoundation/as3hx/issues/46
