### ISSUE TITLE
Unable to translate for loops that run on the length of Object Vectors followed by if check on Object

### ISSUE THREAD

**Issue by jrdoughty** [HaxeFoundation/as3hx#323]
This code breaks the as3hx script in the event that the loop is immediately followed by an if check 

as3 code for example:
```actionscript
package {
    public class Issue {
	private var friendsList:Vector.<Object>;
        public function Issue()
        {
             for ( var i:int = 0; i < friendsList.length; i++ ) 
             { 
                  if ( friendsList[i].bSelected ) 
                      true; 
             }
        }
    }
}
```
expected result
```haxe

class Issue323
{
    private var friendsList:Vector<Dynamic>;
    public function new()
    {
        var i : Int = 0;
        while (i < friendsList.length)
        {
            if( friendsList[i].bSelected ) 
                true;
            i++;
        }

```
actual result
```haxe

class Issue323
{
    public function new()
    {
        var i : Int = 0;
        while (i < friendsList.length)

```
And it crashes, preventing further compilation

Working as3 code requires removing the if check:
```actionscript
package {
    public class Issue {
	private var friendsList:Vector.<Object>;
        private function Issue():void {
            	    for ( var i:int = 0; i < friendsList.length; i++ ) {  true; }
		}
        }
    }
}
```
Last lines of as3hx before crash:

(26) parseExpr(TConst(CInt(0))) [Parser 19]
                        (26) parseExprNext(EConst(CInt(0))) (TSemicolon) [Parser 132]
                        (26) parseExprNext stopped at TSemicolon [Parser 313]
                        (0) TSemicolon to TSemicolon ?= TComma [Parser 286]
                        (26) parseExprNext(EVars([{ name => i, t => TPath([int]), val => ETypedExpr(EConst(CInt(0)),TPath([int])) }])) (TSemicolon) [Parser 132]
                        (26) parseExprNext stopped at TSemicolon [Parser 313]
                        (0) TSemicolon to TSemicolon ?= TComma [Parser 286]
                        (26) parseExprList() [Parser 336]
                        (0) TId(i) to TId(i) ?= TSemicolon [Parser 286]
                        (26) parseExpr(TId(i)) [Parser 19]
                        (26) parseStructure(i) [Parser 16]
                        (26) parseExprNext(EIdent(i)) (TOp(<)) [Parser 132]
                        (26) parseExpr(TId(friendsList)) [Parser 19]
                        (26) parseStructure(friendsList) [Parser 16]
                        (26) parseExprNext(EIdent(friendsList)) (TDot) [Parser 132]
                        (26) TId(length) [Parser 194]
                        (0) TSemicolon to TSemicolon ?= TNs [Parser 286]
                        (26) parseExprNext(EField(EIdent(friendsList),length)) (TSemicolon) [Parser 132]
                        (26) parseExprNext stopped at TSemicolon [Parser 313]
                        (26) parseExprList() [Parser 336]
                        (0) TId(i) to TId(i) ?= TPClose [Parser 286]
                        (26) parseExpr(TId(i)) [Parser 19]
                        (26) parseStructure(i) [Parser 16]
                        (26) parseExprNext(EIdent(i)) (TOp(++)) [Parser 132]
                        (26) parseExprNext(EUnop(++,false,EIdent(i))) (TPClose) [Parser 132]
                        (26) parseExprNext stopped at TPClose [Parser 313]
                        (26) parseExpr(TBrOpen) [Parser 19]
                        (26) parseExpr: TId(if) [Parser 38]
                        (0) TId(if) to TId(if) ?= TBrClose [Parser 286]
                        (26) parseFullExpr() [Parser 321]
                        (26) parseExpr(TId(if)) [Parser 19]
                        (26) parseStructure(if) [Parser 16]
                        (26) parseExpr(TId(friendsList)) [Parser 19]
                        (26) parseStructure(friendsList) [Parser 16]
                        (26) parseExprNext(EIdent(friendsList)) (TBkOpen) [Parser 132]
                        (26) parseExpr(TId(i)) [Parser 19]
                        (26) parseStructure(i) [Parser 16]
                        (26) parseExprNext(EIdent(i)) (TBkClose) [Parser 132]
                        (26) parseExprNext stopped at TBkClose [Parser 313]
                        (26) parseExprNext(EArray(EIdent(friendsList),EIdent(i))) (TDot) [Parser 132]
                        (26) TId(bSelected) [Parser 194]
                        (0) TPClose to TPClose ?= TNs [Parser 286]
                        (26) parseExprNext(EField(EArray(EIdent(friendsList),EIdent(i)),bSelected)) (TPClose) [Parser 132]
                        (26) parseExprNext stopped at TPClose [Parser 313]
                        (26) parseExpr(TId(true)) [Parser 19]
                        (26) parseStructure(true) [Parser 16]
                        (26) parseExprNext(EIdent(true)) (TSemicolon) [Parser 132]
                        (26) parseExprNext stopped at TSemicolon [Parser 313]
                        (26) function end() [Parser 451]
                                (0) TSemicolon to TSemicolon ?= TSemicolon [Parser 286]
                                (0) TBrClose to TBrClose ?= TSemicolon [Parser 286]
                        (26) function end() [Parser 454]
                        (0) TBrClose to TBrClose ?= TId(else) [Parser 286]
                        (0) TBrClose to TBrClose ?= TColon [Parser 286]
                        (0) TBrClose to TBrClose ?= TComma [Parser 286]
                        (26) function end() [Parser 451]
                                (0) TBrClose to TBrClose ?= TSemicolon [Parser 286]
                        (26) function end() [Parser 454]
                        (0) TBrClose to TBrClose ?= TBrClose [Parser 286]
                        (0) TNL(TBrClose) to TBrClose ?= TColon [Parser 286]
                        (0) TNL(TBrClose) to TBrClose ?= TComma [Parser 286]
                        (27) function end() [Parser 451]
                                (0) TNL(TBrClose) to TBrClose ?= TSemicolon [Parser 286]
                        (27) function end() [Parser 454]
                        (0) TNL(TBrClose) to TBrClose ?= TBrClose [Parser 286]
                (27) end parseFun() [Parser 143]
                (27) function end() [Parser 451]
                        (0) TNL(TNL(TBrClose)) to TBrClose ?= TSemicolon [Parser 286]
                (29) function end() [Parser 454]
        (29) end parseClassFun() [Parser 307]
        (0) TNL(TNL(TBrClose)) to TNL(TNL(TBrClose)) ?= TBrClose [Parser 321]
(29) parseClass(Issue) finished [Parser 245]
Called from sys.io.FileOutput::$statics line 1
Called from Run::main line 110
Called from Run::loop line 63
Called from as3hx.Writer::process line 3635
Called from as3hx.Writer::writeDefinitions line 253
Called from as3hx.Writer::writeDefinition line 260
Called from as3hx.Writer::writeClassDef line 329
Called from as3hx.Writer::writeFields line 462
Called from as3hx.Writer::writeField line 606
Called from as3hx.Writer::writeConstructor line 858
Called from as3hx.Writer::writeExpr line 1194
Called from as3hx.Writer::writeEBlock line 1521
Called from as3hx.Writer::writeExpr line 1473
Called from as3hx.Writer::writeExpr line 1202
Called from as3hx.Writer::writeExpr line 1202
Uncaught exception - Invalid field access : index

**Comment by SlavaRa** [comment]
I will fix it tonight

**Comment by jrdoughty** [comment]
Sweet, thank you! I really appreciate it!
