### ISSUE TITLE
Uncaught exception - std@sys_read_dir

### ISSUE THREAD

**Issue by jadbox** [HaxeFoundation/as3hx#46]
> neko run.n swf_src/ out/
Called from sys.io.FileOutput::$statics line 1
Called from Run::main line 102
Called from Run::loop line 33
Called from sys.FileSystem::readDirectory line 85
Uncaught exception - std@sys_read_dir

**Versions:**
NekoVM 2.0.0
Haxe Compiler 3.1.3

**Dir permissions:**
drwxr-xr-x  3 jadbox jadbox   4096 Mar 14 20:32 out
drwxr-xr-x  3 jadbox jadbox   4096 Mar 14 20:32 swf_src

**My OS:** Debian Jessie
swf_src/ folder contains regular AS3 class files

**Comment by giabao** [comment]
Remove the `out/` dir to bypass the error
