### ISSUE TITLE
Dictionary parsing error Unexpected  "="

### ISSUE THREAD

**Issue by T1mL3arn** [HaxeFoundation/as3hx#54]
Code like this

``` as3
private var _displayDataDictionary:Dictionary = new Dictionary();
```

and this

``` as3
function parseSkeletonData(outputAnimationDictionary:Dictionary = null):DragonBonesData
```

prints

```
ERRORS: These files were not written due to source parsing errors:
In C:/HaxeToolkit/dragonbones-as3hx/as3/dragonBones/factories/BaseFactory.as(37): Unexpected =
In C:/HaxeToolkit/dragonbones-as3hx/as3/dragonBones/objects/DragonBonesData.as(13) :Unexpected =
```

and other similar errors with "=" and Dictionary

Is Dictionary parsing not supported? `dictionaryToHash` param is true, but seems it's not working.

**Comment by T1mL3arn** [comment]
Ah, now I see that it works only with Dictionary.<K,V> syntax :(

**Comment by SlavaRa** [comment]
can not reproduce

**Comment by T1mL3arn** [comment]
Issue happens if set ```dictionaryToHash``` to ```true``` in ```.as3hx_config.xml``` file.

**Comment by SlavaRa** [comment]
@T1mL3arn thanks, i will check today
