### ISSUE TITLE
Unexpected : parsing object with newline before first key

### ISSUE THREAD

**Issue by jcward** [HaxeFoundation/as3hx#56]
An object literal (like this one) with a newline between the `{` and the first key dies with `Unexpected :`

```
      var pnt = {
        x:10,
        y:10
      };
```

By contrast, this one works fine, indicating it's probably just a whitespace issue:

```
      var pnt = { x:10,
        y:10
      };
```

**Comment by SlavaRa** [comment]
@jcward please check the last release, and close this issue if all ok

**Comment by jcward** [comment]
Looks good!

**Comment by SlavaRa** [comment]
@jcward  thanks
